# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://mzyy94.com
baseurl: ""
title: 犬アイコンのみっきー
subtitle:
description:
author: mzyy94
logo: https://avatars3.githubusercontent.com/mzyy94?v=3&s=32

# ----------------------- #
#     Link & Markdown     #
# ----------------------- #

baseurl: ""
permalink: /blog/:year/:month/:day/:title/
relative_permalinks: false
aboutme:
  url: /about/
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  enable_coderay: false
  syntax_highlighter: rouge
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  footnote_nr:    1
highlighter: rouge
lsi: false

# ----------------------- #
#    Paginate & Excerpt   #
# ----------------------- #

paginate: 10
paginate_path: "/blog/page/:num"
excerpt_link: "Read more"
excerpt_separator: "<!-- more -->"
recent_posts: 5

# ----------------------- #
#      Locale & Date      #
# ----------------------- #

lang: ja
date_format: "ordinal"
timezone: Asia/Tokyo

# ----------------------- #
#           Sass          #
# ----------------------- #

sass:
  sass_dir: spectre/src
  style: compressed

# ----------------------- #
#  RSS & Search & Comment #
# ----------------------- #

search_engine: https://www.google.com/search
feed:
  path: /blog/atom.xml
disqus_short_name: mzyy94blog

# ----------------------- #
#        Generate         #
# ----------------------- #

exclude:
  - README.md
  - CNAME
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - spectre

# ----------------------- #
#        Defaults         #
# ----------------------- #
defaults:
  - scope:
      path: "assets/stylesheets/syntax.css"
    values:
      defered_css: true
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post

# ----------------------- #
#        SNS Share        #
# ----------------------- #

twitter_share_button: true
hatena_bookmark_button: true
google_plus_button: true
facebook_like_button: true
pocket_save_button: true

# ----------------------- #
#       Analytics         #
# ----------------------- #

google_analytics_tracking_id: UA-41944495-3

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #
gems:
  - jekyll-avatar
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-default-layout
  - jekyll-optional-front-matter
  - jekyll-redirect-from
  - jemoji

# Mentions
jekyll-mentions: https://twitter.com
# Github repositories
repository: mzyy94/mzyy94.github.io
# SEO tag
twitter:
  username: mzyy94
