# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://mzyy94.com
baseurl: ""
title: 犬アイコンのみっきー
title_separator          : "-"
subtitle:
description: いろいろ書く。
name: &id mzyy94
repository: mzyy94/mzyy94.github.io
logo: /assets/images/logo.png

remote_theme: mmistakes/minimal-mistakes@4.18.1
minimal_mistakes_skin: contrast

# ----------------------- #
#          Author         #
# ----------------------- #

author:
  name             : "mzyy94"
  fullname         : "Yuki MIZUNO"
  avatar           : https://avatars3.githubusercontent.com/mzyy94?v=3&s=192
  bio              : 何かしら生きた証を遺したい (575)
  location         : Tokyo
  links:
  - label: "Website"
    icon: "fas fa-fw fa-link"
    url: https://mzyy94.com
  - label: "Keybase"
    icon: "fas fa-fw fa-key"
    url: https://keybase.io/mzyy94
  - label: "Twitter"
    icon: "fab fa-fw fa-twitter-square"
    url: https://twitter.com/mzyy94
  - label: "Bitbucket"
    icon: "fab fa-fw fa-bitbucket"
    url: https://bitbucket.org/mzyy94
  - label: "GitHub"
    icon: "fab fa-fw fa-github"
    url: https://github.com/mzyy94
  - label: "GitLab"
    icon: "fab fa-fw fa-gitlab"
    url: https://gitlab.com/mzyy94
  - label: "Foursquare"
    icon: "fab fa-fw fa-foursquare"
    url: https://foursquare.com/mzyy94
  - label: "Steam"
    icon: "fab fa-fw fa-steam"
    url: https://steamcommunity.com/id/RockingUniform
  - label: "SlideShare"
    icon: "fab fa-fw fa-slideshare"
    url: https://www.slideshare.net/mzyy94
  - label: "Twitch"
    icon: "fab fa-fw fa-twitch"
    url: https://www.twitch.tv/mzyy94
  - label: "Wishlist"
    icon: "fab fa-fw fa-amazon"
    url: https://amzn.mzyy94.com
  - label: "PayPal"
    icon: "fab fa-fw fa-paypal"
    url: https://www.paypal.me/mzyy94



# ----------------------- #
#     Link & Markdown     #
# ----------------------- #

baseurl: ""
permalink: /blog/:year/:month/:day/:title/
relative_permalinks: false
aboutme:
  url: /about/
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  enable_coderay: false
  syntax_highlighter: rouge
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  footnote_nr:    1
highlighter: rouge
lsi: false

# ----------------------- #
#           Sass          #
# ----------------------- #

sass:
  style: compressed

# ----------------------- #
#    Paginate & Excerpt   #
# ----------------------- #

paginate: 10
paginate_path: "/blog/page:num"
excerpt_link: "Read more"
excerpt_separator: "<!-- more -->"
recent_posts: 5

# ----------------------- #
#      Locale & Date      #
# ----------------------- #

lang: ja
locale: ja-JP
date_format: "ordinal"
timezone: Asia/Tokyo

# ----------------------- #
#  RSS & Search & Comment #
# ----------------------- #

#search_engine: https://www.google.com/search
search: true
search_full_content: true
feed:
  path: /blog/atom.xml
atom_feed:
  path: /blog/atom.xml
#discus-identifier: mzyy94blog
comments:
  provider: "disqus"
  disqus:
    shortname: mzyy94blog

# ----------------------- #
#        Generate         #
# ----------------------- #

exclude:
  - README.md
  - CNAME
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - vendor

# ----------------------- #
#        Defaults         #
# ----------------------- #
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      toc: true
      author_profile: true
      comments: true
      share: true
      related: true
      read_time: false
      toc_sticky: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
      read_time: false

# ----------------------- #
#        SNS Share        #
# ----------------------- #

twitter:
  username: *id
# Mentions
jekyll-mentions: https://twitter.com

# ----------------------- #
#    Analytics & SEO      #
# ----------------------- #

analytics:
  provider: google
  google:
    tracking_id: UA-41944495-3
google_site_verification : 

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #
plugins:
  - jekyll-avatar
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-default-layout
  - jekyll-optional-front-matter
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-include-cache
  - jemoji


# ----------------------- #
#         Archives        #
# ----------------------- #
category_archive:
  type: liquid
  path: /blog/categories/
tag_archive:
  type: liquid
  path: /blog/tags/

# ----------------------- #
#         Scripts         #
# ----------------------- #
after_footer_scripts:
  - https://platform.twitter.com/widgets.js
